version: '3.8'

networks:
  deploy-guide-dev:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - deploy-guide-dev
    restart: unless-stopped

  go-app-8080:
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    container_name: go-app-8080
    ports:
      - "8080:8080"
    networks:
      - deploy-guide-dev
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: unless-stopped

  go-app-8000:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    container_name: go-app-8000
    ports:
      - "8000:8000"
    networks:
      - deploy-guide-dev
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo-data:
